# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polektor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 344)
        self.lbl_tensi = QtWidgets.QLabel(Form)
        self.lbl_tensi.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.lbl_tensi.setObjectName("lbl_tensi")
        self.lbl_suhu = QtWidgets.QLabel(Form)
        self.lbl_suhu.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.lbl_suhu.setObjectName("lbl_suhu")
        self.lbl_bpm = QtWidgets.QLabel(Form)
        self.lbl_bpm.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.lbl_bpm.setObjectName("lbl_bpm")
        self.lbl_spo2 = QtWidgets.QLabel(Form)
        self.lbl_spo2.setGeometry(QtCore.QRect(10, 70, 121, 17))
        self.lbl_spo2.setObjectName("lbl_spo2")
        self.btn_measure = QtWidgets.QPushButton(Form)
        self.btn_measure.setGeometry(QtCore.QRect(300, 40, 89, 25))
        self.btn_measure.setObjectName("btn_measure")
        self.btn_refresh = QtWidgets.QPushButton(Form)
        self.btn_refresh.setGeometry(QtCore.QRect(210, 40, 89, 25))
        self.btn_refresh.setObjectName("btn_refresh")
        self.cb_serial = QtWidgets.QComboBox(Form)
        self.cb_serial.setGeometry(QtCore.QRect(210, 10, 181, 25))
        self.cb_serial.setObjectName("cb_serial")
        self.cb_serial.addItem("")
        self.in_nama = QtWidgets.QLineEdit(Form)
        self.in_nama.setGeometry(QtCore.QRect(120, 140, 113, 25))
        self.in_nama.setObjectName("in_nama")
        self.in_nik = QtWidgets.QLineEdit(Form)
        self.in_nik.setGeometry(QtCore.QRect(120, 170, 113, 25))
        self.in_nik.setObjectName("in_nik")
        self.btn_generate = QtWidgets.QPushButton(Form)
        self.btn_generate.setGeometry(QtCore.QRect(120, 290, 111, 25))
        self.btn_generate.setObjectName("btn_generate")
        self.lbl_pw = QtWidgets.QLabel(Form)
        self.lbl_pw.setGeometry(QtCore.QRect(10, 290, 101, 17))
        self.lbl_pw.setObjectName("lbl_pw")
        self.cb_kelamin = QtWidgets.QComboBox(Form)
        self.cb_kelamin.setGeometry(QtCore.QRect(120, 200, 111, 25))
        self.cb_kelamin.setObjectName("cb_kelamin")
        self.cb_kelamin.addItem("")
        self.cb_kelamin.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 140, 51, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 31, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 101, 17))
        self.label_4.setObjectName("label_4")
        self.cb_masaberlaku = QtWidgets.QComboBox(Form)
        self.cb_masaberlaku.setGeometry(QtCore.QRect(120, 260, 111, 25))
        self.cb_masaberlaku.setObjectName("cb_masaberlaku")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.lbl_time = QtWidgets.QLabel(Form)
        self.lbl_time.setGeometry(QtCore.QRect(10, 110, 221, 17))
        self.lbl_time.setObjectName("lbl_time")
        self.btn_validation = QtWidgets.QPushButton(Form)
        self.btn_validation.setGeometry(QtCore.QRect(210, 70, 89, 25))
        self.btn_validation.setObjectName("btn_validation")
        self.in_umur = QtWidgets.QLineEdit(Form)
        self.in_umur.setGeometry(QtCore.QRect(120, 230, 113, 25))
        self.in_umur.setObjectName("in_umur")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 101, 17))
        self.label_5.setObjectName("label_5")
        self.lbl_kategori = QtWidgets.QLabel(Form)
        self.lbl_kategori.setGeometry(QtCore.QRect(10, 90, 67, 17))
        self.lbl_kategori.setObjectName("lbl_kategori")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 50, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(140, 70, 67, 17))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        self.cb_masaberlaku.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_tensi.setText(_translate("Form", ": 0/0"))
        self.lbl_suhu.setText(_translate("Form", ": 0"))
        self.lbl_bpm.setText(_translate("Form", ": 0"))
        self.lbl_spo2.setText(_translate("Form", ": 0"))
        self.btn_measure.setText(_translate("Form", "Measure"))
        self.btn_refresh.setText(_translate("Form", "Refresh"))
        self.cb_serial.setItemText(0, _translate("Form", "None"))
        self.in_nama.setText(_translate("Form", "dummy"))
        self.in_nik.setText(_translate("Form", "170170"))
        self.btn_generate.setText(_translate("Form", "Generate"))
        self.lbl_pw.setText(_translate("Form", "-"))
        self.cb_kelamin.setItemText(0, _translate("Form", "Pria"))
        self.cb_kelamin.setItemText(1, _translate("Form", "Wanita"))
        self.label.setText(_translate("Form", "Nama"))
        self.label_2.setText(_translate("Form", "NIK"))
        self.label_3.setText(_translate("Form", "Jenis Kelamin"))
        self.label_4.setText(_translate("Form", "Masa Berlaku"))
        self.cb_masaberlaku.setItemText(0, _translate("Form", "1 Hari"))
        self.cb_masaberlaku.setItemText(1, _translate("Form", "2 Hari"))
        self.cb_masaberlaku.setItemText(2, _translate("Form", "3 Hari"))
        self.cb_masaberlaku.setItemText(3, _translate("Form", "4 Hari"))
        self.cb_masaberlaku.setItemText(4, _translate("Form", "5 Hari"))
        self.cb_masaberlaku.setItemText(5, _translate("Form", "6 Hari"))
        self.cb_masaberlaku.setItemText(6, _translate("Form", "7 Hari"))
        self.lbl_time.setText(_translate("Form", "11/05/2021"))
        self.btn_validation.setText(_translate("Form", "Publish"))
        self.in_umur.setText(_translate("Form", "21"))
        self.label_5.setText(_translate("Form", "Umur"))
        self.lbl_kategori.setText(_translate("Form", ": Positif"))
        self.label_6.setText(_translate("Form", "mmHg"))
        self.label_7.setText(_translate("Form", "Celcius"))
        self.label_8.setText(_translate("Form", "BPM"))
        self.label_9.setText(_translate("Form", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
