# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polektor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 659)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 200, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 166, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 89, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 194, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 200, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 166, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 89, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 194, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 200, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 166, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 89, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 66, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 133, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Form.setPalette(palette)
        self.key_q = QtWidgets.QPushButton(Form)
        self.key_q.setGeometry(QtCore.QRect(20, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_q.setFont(font)
        self.key_q.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_q.setObjectName("key_q")
        self.key_w = QtWidgets.QPushButton(Form)
        self.key_w.setGeometry(QtCore.QRect(90, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_w.setFont(font)
        self.key_w.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_w.setObjectName("key_w")
        self.key_e = QtWidgets.QPushButton(Form)
        self.key_e.setGeometry(QtCore.QRect(160, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_e.setFont(font)
        self.key_e.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_e.setObjectName("key_e")
        self.key_r = QtWidgets.QPushButton(Form)
        self.key_r.setGeometry(QtCore.QRect(230, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_r.setFont(font)
        self.key_r.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_r.setObjectName("key_r")
        self.key_t = QtWidgets.QPushButton(Form)
        self.key_t.setGeometry(QtCore.QRect(300, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_t.setFont(font)
        self.key_t.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_t.setObjectName("key_t")
        self.key_y = QtWidgets.QPushButton(Form)
        self.key_y.setGeometry(QtCore.QRect(370, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_y.setFont(font)
        self.key_y.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_y.setObjectName("key_y")
        self.key_i = QtWidgets.QPushButton(Form)
        self.key_i.setGeometry(QtCore.QRect(510, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_i.setFont(font)
        self.key_i.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_i.setObjectName("key_i")
        self.key_o = QtWidgets.QPushButton(Form)
        self.key_o.setGeometry(QtCore.QRect(580, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_o.setFont(font)
        self.key_o.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_o.setObjectName("key_o")
        self.key_p = QtWidgets.QPushButton(Form)
        self.key_p.setGeometry(QtCore.QRect(650, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_p.setFont(font)
        self.key_p.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_p.setObjectName("key_p")
        self.key_u = QtWidgets.QPushButton(Form)
        self.key_u.setGeometry(QtCore.QRect(440, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_u.setFont(font)
        self.key_u.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_u.setObjectName("key_u")
        self.key_a = QtWidgets.QPushButton(Form)
        self.key_a.setGeometry(QtCore.QRect(20, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_a.setFont(font)
        self.key_a.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_a.setObjectName("key_a")
        self.key_s = QtWidgets.QPushButton(Form)
        self.key_s.setGeometry(QtCore.QRect(90, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_s.setFont(font)
        self.key_s.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_s.setObjectName("key_s")
        self.key_f = QtWidgets.QPushButton(Form)
        self.key_f.setGeometry(QtCore.QRect(230, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_f.setFont(font)
        self.key_f.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_f.setObjectName("key_f")
        self.key_j = QtWidgets.QPushButton(Form)
        self.key_j.setGeometry(QtCore.QRect(440, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_j.setFont(font)
        self.key_j.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_j.setObjectName("key_j")
        self.key_k = QtWidgets.QPushButton(Form)
        self.key_k.setGeometry(QtCore.QRect(510, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_k.setFont(font)
        self.key_k.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_k.setObjectName("key_k")
        self.key_h = QtWidgets.QPushButton(Form)
        self.key_h.setGeometry(QtCore.QRect(370, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_h.setFont(font)
        self.key_h.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_h.setObjectName("key_h")
        self.key_d = QtWidgets.QPushButton(Form)
        self.key_d.setGeometry(QtCore.QRect(160, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_d.setFont(font)
        self.key_d.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_d.setObjectName("key_d")
        self.key_l = QtWidgets.QPushButton(Form)
        self.key_l.setGeometry(QtCore.QRect(580, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_l.setFont(font)
        self.key_l.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_l.setObjectName("key_l")
        self.key_g = QtWidgets.QPushButton(Form)
        self.key_g.setGeometry(QtCore.QRect(300, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_g.setFont(font)
        self.key_g.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_g.setObjectName("key_g")
        self.key_x = QtWidgets.QPushButton(Form)
        self.key_x.setGeometry(QtCore.QRect(90, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_x.setFont(font)
        self.key_x.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_x.setObjectName("key_x")
        self.key_v = QtWidgets.QPushButton(Form)
        self.key_v.setGeometry(QtCore.QRect(230, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_v.setFont(font)
        self.key_v.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_v.setObjectName("key_v")
        self.key_comma = QtWidgets.QPushButton(Form)
        self.key_comma.setGeometry(QtCore.QRect(510, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_comma.setFont(font)
        self.key_comma.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_comma.setObjectName("key_comma")
        self.key_z = QtWidgets.QPushButton(Form)
        self.key_z.setGeometry(QtCore.QRect(20, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_z.setFont(font)
        self.key_z.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_z.setObjectName("key_z")
        self.key_m = QtWidgets.QPushButton(Form)
        self.key_m.setGeometry(QtCore.QRect(440, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_m.setFont(font)
        self.key_m.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_m.setObjectName("key_m")
        self.key_b = QtWidgets.QPushButton(Form)
        self.key_b.setGeometry(QtCore.QRect(300, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_b.setFont(font)
        self.key_b.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_b.setObjectName("key_b")
        self.key_c = QtWidgets.QPushButton(Form)
        self.key_c.setGeometry(QtCore.QRect(160, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_c.setFont(font)
        self.key_c.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_c.setObjectName("key_c")
        self.key_n = QtWidgets.QPushButton(Form)
        self.key_n.setGeometry(QtCore.QRect(370, 520, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_n.setFont(font)
        self.key_n.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_n.setObjectName("key_n")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 711, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(400, 100, 101, 17))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 51, 17))
        self.label_2.setObjectName("label_2")
        self.lbl_pw = QtWidgets.QLabel(self.groupBox)
        self.lbl_pw.setGeometry(QtCore.QRect(480, 140, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_pw.setFont(font)
        self.lbl_pw.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pw.setObjectName("lbl_pw")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(400, 40, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 101, 17))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 17))
        self.label.setObjectName("label")
        self.btn_generate = QtWidgets.QPushButton(self.groupBox)
        self.btn_generate.setGeometry(QtCore.QRect(630, 110, 71, 61))
        self.btn_generate.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_generate.setCheckable(False)
        self.btn_generate.setDefault(False)
        self.btn_generate.setFlat(False)
        self.btn_generate.setObjectName("btn_generate")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(400, 60, 101, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 101, 17))
        self.label_12.setObjectName("label_12")
        self.cb_masaberlaku = QtWidgets.QComboBox(self.groupBox)
        self.cb_masaberlaku.setGeometry(QtCore.QRect(100, 140, 291, 41))
        self.cb_masaberlaku.setObjectName("cb_masaberlaku")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_masaberlaku.addItem("")
        self.cb_kelamin = QtWidgets.QComboBox(self.groupBox)
        self.cb_kelamin.setGeometry(QtCore.QRect(480, 40, 141, 41))
        self.cb_kelamin.setObjectName("cb_kelamin")
        self.cb_kelamin.addItem("")
        self.cb_kelamin.addItem("")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(400, 140, 101, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(400, 160, 101, 17))
        self.label_14.setObjectName("label_14")
        self.btn_reset = QtWidgets.QPushButton(self.groupBox)
        self.btn_reset.setGeometry(QtCore.QRect(630, 40, 71, 61))
        self.btn_reset.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_reset.setObjectName("btn_reset")
        self.in_nama = QtWidgets.QPushButton(self.groupBox)
        self.in_nama.setEnabled(True)
        self.in_nama.setGeometry(QtCore.QRect(100, 40, 291, 41))
        self.in_nama.setText("")
        self.in_nama.setCheckable(False)
        self.in_nama.setChecked(False)
        self.in_nama.setObjectName("in_nama")
        self.in_nik = QtWidgets.QPushButton(self.groupBox)
        self.in_nik.setGeometry(QtCore.QRect(100, 90, 291, 41))
        self.in_nik.setObjectName("in_nik")
        self.in_umur = QtWidgets.QPushButton(self.groupBox)
        self.in_umur.setGeometry(QtCore.QRect(480, 90, 141, 41))
        self.in_umur.setText("")
        self.in_umur.setObjectName("in_umur")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(730, 100, 271, 481))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(100, 73, 81, 31))
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(190, 100, 67, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(190, 150, 67, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(190, 200, 67, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(190, 250, 67, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 67, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 200, 81, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 250, 67, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.in_spo2 = QtWidgets.QPushButton(self.groupBox_2)
        self.in_spo2.setGeometry(QtCore.QRect(90, 240, 91, 41))
        self.in_spo2.setObjectName("in_spo2")
        self.in_bpm = QtWidgets.QPushButton(self.groupBox_2)
        self.in_bpm.setGeometry(QtCore.QRect(90, 190, 91, 41))
        self.in_bpm.setObjectName("in_bpm")
        self.in_suhu = QtWidgets.QPushButton(self.groupBox_2)
        self.in_suhu.setGeometry(QtCore.QRect(90, 140, 91, 41))
        self.in_suhu.setObjectName("in_suhu")
        self.in_sys = QtWidgets.QPushButton(self.groupBox_2)
        self.in_sys.setGeometry(QtCore.QRect(90, 40, 91, 41))
        self.in_sys.setObjectName("in_sys")
        self.in_dias = QtWidgets.QPushButton(self.groupBox_2)
        self.in_dias.setGeometry(QtCore.QRect(90, 90, 91, 41))
        self.in_dias.setObjectName("in_dias")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(190, 50, 67, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.btn_measure_suhu = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_measure_suhu.setGeometry(QtCore.QRect(10, 300, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_measure_suhu.setFont(font)
        self.btn_measure_suhu.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_measure_suhu.setObjectName("btn_measure_suhu")
        self.btn_measure_oxi = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_measure_oxi.setGeometry(QtCore.QRect(10, 360, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_measure_oxi.setFont(font)
        self.btn_measure_oxi.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_measure_oxi.setObjectName("btn_measure_oxi")
        self.btn_measure_tensi = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_measure_tensi.setGeometry(QtCore.QRect(10, 420, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_measure_tensi.setFont(font)
        self.btn_measure_tensi.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_measure_tensi.setObjectName("btn_measure_tensi")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(1010, 200, 261, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.cb_serial = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_serial.setGeometry(QtCore.QRect(10, 100, 241, 51))
        self.cb_serial.setObjectName("cb_serial")
        self.cb_serial.addItem("")
        self.btn_refresh = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_refresh.setGeometry(QtCore.QRect(10, 40, 241, 51))
        self.btn_refresh.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_refresh.setObjectName("btn_refresh")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(1010, 100, 261, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 220, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 124, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 93, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 186, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.groupBox_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lbl_time = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_time.setGeometry(QtCore.QRect(10, 16, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_time.setFont(font)
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_jam = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_jam.setGeometry(QtCore.QRect(150, 11, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_jam.setFont(font)
        self.lbl_jam.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_jam.setObjectName("lbl_jam")
        self.key_enter = QtWidgets.QPushButton(Form)
        self.key_enter.setGeometry(QtCore.QRect(580, 590, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_enter.setFont(font)
        self.key_enter.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_enter.setObjectName("key_enter")
        self.key_del = QtWidgets.QPushButton(Form)
        self.key_del.setGeometry(QtCore.QRect(650, 450, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.key_del.setFont(font)
        self.key_del.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_del.setObjectName("key_del")
        self.btn_validation = QtWidgets.QPushButton(Form)
        self.btn_validation.setGeometry(QtCore.QRect(730, 590, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_validation.setFont(font)
        self.btn_validation.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_validation.setObjectName("btn_validation")
        self.key_space = QtWidgets.QPushButton(Form)
        self.key_space.setGeometry(QtCore.QRect(20, 590, 551, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_space.setFont(font)
        self.key_space.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_space.setObjectName("key_space")
        self.key_1 = QtWidgets.QPushButton(Form)
        self.key_1.setGeometry(QtCore.QRect(20, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_1.setFont(font)
        self.key_1.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_1.setObjectName("key_1")
        self.key_2 = QtWidgets.QPushButton(Form)
        self.key_2.setGeometry(QtCore.QRect(90, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_2.setFont(font)
        self.key_2.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_2.setObjectName("key_2")
        self.key_3 = QtWidgets.QPushButton(Form)
        self.key_3.setGeometry(QtCore.QRect(160, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_3.setFont(font)
        self.key_3.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_3.setObjectName("key_3")
        self.key_5 = QtWidgets.QPushButton(Form)
        self.key_5.setGeometry(QtCore.QRect(300, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_5.setFont(font)
        self.key_5.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_5.setObjectName("key_5")
        self.key_6 = QtWidgets.QPushButton(Form)
        self.key_6.setGeometry(QtCore.QRect(370, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_6.setFont(font)
        self.key_6.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_6.setObjectName("key_6")
        self.key_4 = QtWidgets.QPushButton(Form)
        self.key_4.setGeometry(QtCore.QRect(230, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_4.setFont(font)
        self.key_4.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_4.setObjectName("key_4")
        self.key_8 = QtWidgets.QPushButton(Form)
        self.key_8.setGeometry(QtCore.QRect(510, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_8.setFont(font)
        self.key_8.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_8.setObjectName("key_8")
        self.key_7 = QtWidgets.QPushButton(Form)
        self.key_7.setGeometry(QtCore.QRect(440, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_7.setFont(font)
        self.key_7.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_7.setObjectName("key_7")
        self.key_9 = QtWidgets.QPushButton(Form)
        self.key_9.setGeometry(QtCore.QRect(580, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_9.setFont(font)
        self.key_9.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_9.setObjectName("key_9")
        self.key_0 = QtWidgets.QPushButton(Form)
        self.key_0.setGeometry(QtCore.QRect(650, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.key_0.setFont(font)
        self.key_0.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_0.setObjectName("key_0")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 261, 81))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(300, 10, 681, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_22.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(320, 50, 641, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Jamrul")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.key_bs = QtWidgets.QPushButton(Form)
        self.key_bs.setGeometry(QtCore.QRect(579, 520, 131, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.key_bs.setFont(font)
        self.key_bs.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.key_bs.setObjectName("key_bs")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(1060, 10, 191, 81))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.btn_exit = QtWidgets.QPushButton(Form)
        self.btn_exit.setGeometry(QtCore.QRect(1010, 590, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_predict = QtWidgets.QPushButton(Form)
        self.btn_predict.setGeometry(QtCore.QRect(1180, 370, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_predict.setFont(font)
        self.btn_predict.setStyleSheet("QPushButton:pressed { background-color: rgb(85, 87, 83)}\n"
"QPushButton:pressed { color:rgb(238, 238, 236)}\n"
"")
        self.btn_predict.setObjectName("btn_predict")
        self.lbl_kategori = QtWidgets.QLabel(Form)
        self.lbl_kategori.setGeometry(QtCore.QRect(1020, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.lbl_kategori.setFont(font)
        self.lbl_kategori.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kategori.setObjectName("lbl_kategori")
        self.console = QtWidgets.QTextEdit(Form)
        self.console.setGeometry(QtCore.QRect(1010, 440, 261, 141))
        self.console.setObjectName("console")

        self.retranslateUi(Form)
        self.cb_masaberlaku.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.key_w, self.key_e)
        Form.setTabOrder(self.key_e, self.key_r)
        Form.setTabOrder(self.key_r, self.key_t)
        Form.setTabOrder(self.key_t, self.key_y)
        Form.setTabOrder(self.key_y, self.key_i)
        Form.setTabOrder(self.key_i, self.key_o)
        Form.setTabOrder(self.key_o, self.key_p)
        Form.setTabOrder(self.key_p, self.key_u)
        Form.setTabOrder(self.key_u, self.key_a)
        Form.setTabOrder(self.key_a, self.key_s)
        Form.setTabOrder(self.key_s, self.key_f)
        Form.setTabOrder(self.key_f, self.key_j)
        Form.setTabOrder(self.key_j, self.key_k)
        Form.setTabOrder(self.key_k, self.key_h)
        Form.setTabOrder(self.key_h, self.key_d)
        Form.setTabOrder(self.key_d, self.key_l)
        Form.setTabOrder(self.key_l, self.key_g)
        Form.setTabOrder(self.key_g, self.key_x)
        Form.setTabOrder(self.key_x, self.key_v)
        Form.setTabOrder(self.key_v, self.key_comma)
        Form.setTabOrder(self.key_comma, self.key_z)
        Form.setTabOrder(self.key_z, self.key_m)
        Form.setTabOrder(self.key_m, self.key_b)
        Form.setTabOrder(self.key_b, self.key_c)
        Form.setTabOrder(self.key_c, self.key_n)
        Form.setTabOrder(self.key_n, self.key_enter)
        Form.setTabOrder(self.key_enter, self.key_del)
        Form.setTabOrder(self.key_del, self.btn_validation)
        Form.setTabOrder(self.btn_validation, self.btn_generate)
        Form.setTabOrder(self.btn_generate, self.key_q)
        Form.setTabOrder(self.key_q, self.cb_masaberlaku)
        Form.setTabOrder(self.cb_masaberlaku, self.cb_kelamin)
        Form.setTabOrder(self.cb_kelamin, self.btn_reset)
        Form.setTabOrder(self.btn_reset, self.btn_predict)
        Form.setTabOrder(self.btn_predict, self.cb_serial)
        Form.setTabOrder(self.cb_serial, self.btn_refresh)
        Form.setTabOrder(self.btn_refresh, self.btn_measure_suhu)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.key_q.setText(_translate("Form", "Q"))
        self.key_w.setText(_translate("Form", "W"))
        self.key_e.setText(_translate("Form", "E"))
        self.key_r.setText(_translate("Form", "R"))
        self.key_t.setText(_translate("Form", "T"))
        self.key_y.setText(_translate("Form", "Y"))
        self.key_i.setText(_translate("Form", "I"))
        self.key_o.setText(_translate("Form", "O"))
        self.key_p.setText(_translate("Form", "P"))
        self.key_u.setText(_translate("Form", "U"))
        self.key_a.setText(_translate("Form", "A"))
        self.key_s.setText(_translate("Form", "S"))
        self.key_f.setText(_translate("Form", "F"))
        self.key_j.setText(_translate("Form", "J"))
        self.key_k.setText(_translate("Form", "K"))
        self.key_h.setText(_translate("Form", "H"))
        self.key_d.setText(_translate("Form", "D"))
        self.key_l.setText(_translate("Form", "L"))
        self.key_g.setText(_translate("Form", "G"))
        self.key_x.setText(_translate("Form", "X"))
        self.key_v.setText(_translate("Form", "V"))
        self.key_comma.setText(_translate("Form", ","))
        self.key_z.setText(_translate("Form", "Z"))
        self.key_m.setText(_translate("Form", "M"))
        self.key_b.setText(_translate("Form", "B"))
        self.key_c.setText(_translate("Form", "C"))
        self.key_n.setText(_translate("Form", "N"))
        self.groupBox.setTitle(_translate("Form", "Personal Data"))
        self.label_5.setText(_translate("Form", "Umur"))
        self.label_2.setText(_translate("Form", "NIK"))
        self.lbl_pw.setText(_translate("Form", "-"))
        self.label_3.setText(_translate("Form", "Jenis"))
        self.label_4.setText(_translate("Form", "Masa"))
        self.label.setText(_translate("Form", "Nama"))
        self.btn_generate.setText(_translate("Form", "GEN"))
        self.label_11.setText(_translate("Form", "Kelamin"))
        self.label_12.setText(_translate("Form", "Berlaku"))
        self.cb_masaberlaku.setItemText(0, _translate("Form", "1 Hari"))
        self.cb_masaberlaku.setItemText(1, _translate("Form", "2 Hari"))
        self.cb_masaberlaku.setItemText(2, _translate("Form", "3 Hari"))
        self.cb_kelamin.setItemText(0, _translate("Form", "PRIA"))
        self.cb_kelamin.setItemText(1, _translate("Form", "WANITA"))
        self.label_13.setText(_translate("Form", "Pass"))
        self.label_14.setText(_translate("Form", "Code"))
        self.btn_reset.setText(_translate("Form", "RST"))
        self.in_nik.setText(_translate("Form", "350"))
        self.groupBox_2.setTitle(_translate("Form", "Measurement Data"))
        self.label_10.setText(_translate("Form", "____________"))
        self.label_6.setText(_translate("Form", "mmHg"))
        self.label_15.setText(_translate("Form", "Celcius"))
        self.label_16.setText(_translate("Form", "BPM"))
        self.label_17.setText(_translate("Form", "%"))
        self.label_7.setText(_translate("Form", "Systole"))
        self.label_18.setText(_translate("Form", "Suhu"))
        self.label_19.setText(_translate("Form", "Jantung"))
        self.label_20.setText(_translate("Form", "SPo2"))
        self.in_spo2.setText(_translate("Form", "98"))
        self.in_bpm.setText(_translate("Form", "70"))
        self.in_suhu.setText(_translate("Form", "36.6"))
        self.in_sys.setText(_translate("Form", "120"))
        self.in_dias.setText(_translate("Form", "80"))
        self.label_8.setText(_translate("Form", "mmHg"))
        self.label_9.setText(_translate("Form", "Diastole"))
        self.btn_measure_suhu.setText(_translate("Form", "Measure Suhu"))
        self.btn_measure_oxi.setText(_translate("Form", "Measure Oxi"))
        self.btn_measure_tensi.setText(_translate("Form", "Measure Tensi"))
        self.groupBox_3.setTitle(_translate("Form", "Serial COM Port"))
        self.cb_serial.setItemText(0, _translate("Form", "None"))
        self.btn_refresh.setText(_translate("Form", "REFRESH"))
        self.groupBox_4.setTitle(_translate("Form", "Time"))
        self.lbl_time.setText(_translate("Form", "11/5/2021"))
        self.lbl_jam.setText(_translate("Form", "99:99:99"))
        self.key_enter.setText(_translate("Form", "ENTER"))
        self.key_del.setText(_translate("Form", "DEL"))
        self.btn_validation.setText(_translate("Form", "PUBLISH"))
        self.key_space.setText(_translate("Form", "SPACE"))
        self.key_1.setText(_translate("Form", "1"))
        self.key_2.setText(_translate("Form", "2"))
        self.key_3.setText(_translate("Form", "3"))
        self.key_5.setText(_translate("Form", "5"))
        self.key_6.setText(_translate("Form", "6"))
        self.key_4.setText(_translate("Form", "4"))
        self.key_8.setText(_translate("Form", "8"))
        self.key_7.setText(_translate("Form", "7"))
        self.key_9.setText(_translate("Form", "9"))
        self.key_0.setText(_translate("Form", "0"))
        self.label_22.setText(_translate("Form", "POLECTOR C-19"))
        self.label_23.setText(_translate("Form", "POLTEKAD Electronic Detector Covid-19"))
        self.key_bs.setText(_translate("Form", "BACKSPACE"))
        self.btn_exit.setText(_translate("Form", "EXIT"))
        self.btn_predict.setText(_translate("Form", "PRED"))
        self.lbl_kategori.setText(_translate("Form", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
